import java.sql.*;

public class OracleJDBCExample {
    public static void main(String[] args) {
        // 🔹 Database connection details
        String url = "jdbc:oracle:thin:@localhost:1521:xe"; // OR service name: @//localhost:1521/XEPDB1
        String user = "college";     // username you created
        String password = "college123"; // password you created

        Connection conn = null;
        Statement stmt = null;
        PreparedStatement pstmt = null;
        ResultSet rs = null;

        try {
            // Load Oracle JDBC Driver
            Class.forName("oracle.jdbc.driver.OracleDriver");
            System.out.println(" Oracle JDBC Driver Loaded.");

            // Establish Connection
            conn = DriverManager.getConnection(url, user, password);
            System.out.println(" Connected to Oracle Database Successfully.");

            // Create Table (if not exists)
            stmt = conn.createStatement();
            String createTable = """
                CREATE TABLE students (
                    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(50),
                    age NUMBER(3),
                    course VARCHAR2(50)
                )
            """;
            try {
                stmt.executeUpdate(createTable);
                System.out.println(" Table 'students' created.");
            } catch (SQLException e) {
                if (e.getErrorCode() == 955) { // ORA-00955 = name already used
                    System.out.println(" Table already exists.");
                } else {
                    throw e;
                }
            }

            // Insert Data using PreparedStatement
            String insertSQL = "INSERT INTO students (name, age, course) VALUES (?, ?, ?)";
            pstmt = conn.prepareStatement(insertSQL);
            pstmt.setString(1, "Amit");
            pstmt.setInt(2, 20);
            pstmt.setString(3, "CSE");
            pstmt.executeUpdate();

            pstmt.setString(1, "Priya");
            pstmt.setInt(2, 22);
            pstmt.setString(3, "ECE");
            pstmt.executeUpdate();

            System.out.println(" Records Inserted Successfully.");

            // Retrieve Data
            rs = stmt.executeQuery("SELECT * FROM students");
            System.out.println("\n🎓 Student Records:");
            System.out.println("----------------------------");
            while (rs.next()) {
                System.out.println(
                        rs.getInt("id") + " | " +
                                rs.getString("name") + " | " +
                                rs.getInt("age") + " | " +
                                rs.getString("course")
                );
            }

            //  Update Record
            String updateSQL = "UPDATE students SET course = ? WHERE name = ?";
            pstmt = conn.prepareStatement(updateSQL);
            pstmt.setString(1, "Information Technology");
            pstmt.setString(2, "Amit");
            pstmt.executeUpdate();
            System.out.println("\n Record Updated Successfully.");

            // Delete Record
            String deleteSQL = "DELETE FROM students WHERE name = ?";
            pstmt = conn.prepareStatement(deleteSQL);
            pstmt.setString(1, "Priya");
            pstmt.executeUpdate();
            System.out.println("🗑️ Record Deleted Successfully.");

        } catch (ClassNotFoundException e) {
            System.out.println(" Oracle JDBC Driver not found.");
        } catch (SQLException e) {
            System.out.println(" Database Error: " + e.getMessage());
        } finally {
            //  Close all connections
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (pstmt != null) pstmt.close();
                if (conn != null) conn.close();
                System.out.println(" All connections closed.");
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
}
